name: Actions Workflow 

on: [push]

jobs:
    run-github-actions:
      runs-on: ubuntu-latest
      steps:
        - names: Simple JS Action
          id: greet
          uses:  actions/hello-world-javascript-action@v1
          with:
            who-to-greet: Chris
        - name: Log Greeting Time
          run: echo "${{ steps.greet.outputs.time }}"

        
        